global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT:-9090}']

  # Expenses Bot
  - job_name: 'expenses-bot'
    static_configs:
      - targets: ['localhost:${BOT_PORT:-3001}']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health check
  - job_name: 'expenses-bot-health'
    static_configs:
      - targets: ['localhost:${BOT_PORT:-3001}']
    metrics_path: '/health'
    scrape_interval: 60s 