server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

  # Application logs
  - job_name: expenses-bot
    static_configs:
      - targets:
          - localhost
        labels:
          job: expenses-bot
          app: expenses-bot
          __path__: /var/log/app/*.log

  # Error logs
  - job_name: expenses-bot-errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: expenses-bot-errors
          app: expenses-bot
          level: error
          __path__: /var/log/app/error-*.log

  # Application logs with JSON parsing
  - job_name: expenses-bot-json
    static_configs:
      - targets:
          - localhost
        labels:
          job: expenses-bot-json
          app: expenses-bot
          __path__: /var/log/app/application-*.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            request_id: request_id
            method: method
            path: path
            status_code: status_code
            duration: duration
            ip: ip
            user_agent: user_agent
            error: error
            stack_trace: stack_trace
            metadata: metadata
      
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      
      - labels:
          level:
          service:
          method:
          status_code:
      
      - output:
          source: message

  # Promtail itself
  - job_name: promtail
    static_configs:
      - targets:
          - localhost
        labels:
          job: promtail
          __path__: /var/log/promtail.log

  # Grafana logs
  - job_name: grafana
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          __path__: /var/log/grafana/*.log

  # Prometheus logs
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost
        labels:
          job: prometheus
          __path__: /var/log/prometheus/*.log

  # Loki logs
  - job_name: loki
    static_configs:
      - targets:
          - localhost
        labels:
          job: loki
          __path__: /var/log/loki/*.log 